- name: Collect and publish a json artifact
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Retrieve a repository from a distant location and make it available locally
    ansible.scm.git_here:
      origin:
        url: git@github.com:cidrblock/fest22.git
    register: cloned_repo

  - name: Collect sample json from a REST API and save in repository
    ansible.builtin.get_url:
      url: https://random-data-api.com/api/beer/random_beer
      dest: "{{ cloned_repo['path'] }}/response.json"
      mode: 0644

  - name: Push the changes back to the origin repository
    ansible.scm.git_away:
      path: "{{ cloned_repo['path'] }}"
