- hosts: localhost
  gather_facts: false
  tasks:
  - name: Retrieve a repository from a distant location and make it available locally
    ansible.scm.git_here:
      origin:
        url: git@github.com:cidrblock/fest22.git

